image: ruby:2.3

pages:
    stage: deploy
    script:
    - gem install jekyll
    - gem install jekyll-gist
    - gem install jekyll-paginate
    - gem install jemoji 
    - jekyll build -d public/
    artifacts:
        paths:
        - public
    only:
    - master