markdown: rdiscount
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "Wuxiang Lin"
markdown: rdiscount

author: "Wuxiang Lin"
atom-baseurl: "http://lywx.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Bio
    class: fa fa-user
    href: /about.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

